"""Curated 2026 issue copy. Facts only; no purchase links."""
from __future__ import annotations

# 8 books per language, first published in 2026 (within last 12 months as of 2026-09-17).
FEATURED = [
    # ---------- English ----------
    {
        "matchTitle": "The Sleeping Sisters",
        "languageCode": "en",
        "chineseTitle": "沉睡的姐妹",
        "publicationDate": "2026-01-01",
        "isbn13": "9780316581554",
        "publisher": "Little, Brown",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "文学小说"],
        "tags": ["文学悬疑", "家庭", "沙漠"],
        "coverImage": "/covers/sleeping-sisters.jpg",
        "editorQuoteZh": "沙漠还没醒，家里的秘密先醒了。",
        "readingMoodZh": "干燥、迟缓、带一点神话余温的文学悬疑。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Little, Brown catalog / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026 年首次出版，且已有可靠 ISBN 与封面。",
        "author": {
            "name": "Jennifer Givhan",
            "localizedName": "詹妮弗·吉凡",
            "nationality": "美国",
            "biographyZh": "詹妮弗·吉凡是美国诗人与小说家，作品常写西南部土地、母系记忆与身体里的不安。她把神话碎片嵌进当代家庭，文字偏诗，节奏不赶。读者若只想要快反转，可能会觉得她慢；若想在悬疑里听见地方与血缘，她的句子会把你按在风景里。",
        },
        "fullDescriptionZh": "新墨西哥的沙漠看似静止，其实一直在发热。一个家庭围着沉睡、照看与等待打转：有人要保护孩子，有人要查清一桩不肯闭上的事，有人感觉脚下的土地比人更先知道结局。吉凡不靠机关把读者往前推，而是让热浪、尘土和家庭里没说完的话慢慢堆积。火山是背景，也是隐喻——不是立刻喷发，而是一直存在。读它需要一点耐心：秘密不是被揭开，而是被烘烤出来的。",
        "recommendationZh": "推荐它，是因为它把悬疑写成气候。人物的恐惧不来自突然的敲门，而来自照顾、血缘和土地互相挤压。文字有诗的密度，却仍是小说的骨架。适合不想把2026年新书读成模板惊悚的人。它慢，但慢得有地形。",
        "audienceZh": "喜欢文学笔法多于机关、能接受西南部神话气质、并对家庭伦理感兴趣的读者。不适合只求每章一个反转的快餐悬疑读者。",
    },
    {
        "matchTitle": "God's Country",
        "languageCode": "en",
        "chineseTitle": "上帝的国度",
        "publicationDate": "2026-08-01",
        "isbn13": "9781668231869",
        "publisher": "Atria",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "推理"],
        "tags": ["荒野", "犯罪", "文学悬疑"],
        "coverImage": "/covers/gods-country.jpg",
        "editorQuoteZh": "边界水域里，风景比人更会设局。",
        "readingMoodZh": "冷、湿、辽阔，像把侦探小说拖进没信号的地方。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Atria / ISBN 9781668231869",
        "sourceUrl": "",
        "selectionReason": "2026年8月新作，ISBN 与作者系列信息可核。",
        "author": {
            "name": "William Kent Krueger",
            "localizedName": "威廉·肯特·克鲁格",
            "nationality": "美国",
            "biographyZh": "克鲁格长期写美国北部森林、湖泊与原住民土地上的罪案，以 Cork O’Connor 系列为人所知。他的推理不急着炫技，更在意地方如何塑造人的选择。句子清楚，道德却不简单。读他像跟着向导进山：路径明确，雾是另外一回事。",
        },
        "fullDescriptionZh": "故事落在边界水域：一具尸体、一个人质，以及一片看起来比法律更古老的荒野。调查必须在天气、地形和人际信任的缝隙里推进。克鲁格擅长让户外本身成为压力——不是风景明信片，而是会改写时间感的现场。人物带着各自的亏欠进来，案子只是把那些亏欠暴露出来。读的时候你会一直问：在这种地方，什么叫保护，什么叫侵入。",
        "recommendationZh": "它证明通俗罪案不必吵。水、树、船与沉默构成节奏，人物的判断被自然环境拉长。2026年英语新书里，这是少有把“地方”写成主要角色的作品。想从城市封闭房间里走出去的悬疑读者，会觉得空气突然变了。",
        "audienceZh": "喜欢户外犯罪、文学气息推理、以及美国北部地方志式叙事的读者。若你只要室内心理游戏，它可能显得太开阔。",
    },
    {
        "matchTitle": "The Best I Never Had",
        "languageCode": "en",
        "chineseTitle": "我从未真正拥有的最好",
        "publicationDate": "2026-08-01",
        "isbn13": "9781250341587",
        "publisher": "St. Martin's Griffin",
        "primaryGenre": "爱情",
        "genres": ["爱情"],
        "tags": ["假约会", "重逢", "轻松浪漫"],
        "coverImage": "/covers/best-i-never-had.jpg",
        "editorQuoteZh": "假的三年，真的一周，婚礼把旧账摊开。",
        "readingMoodZh": "轻、热、带着一点尴尬的甜。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "St. Martin's Griffin / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026年8月出版的英语浪漫小说，封面资料完整。",
        "author": {
            "name": "Amy Buchanan",
            "localizedName": "艾米·布坎南",
            "nationality": "美国",
            "biographyZh": "艾米·布坎南写当代英语浪漫，擅长把误会、亲密和自尊放在同一张社交桌面上。她的对话快，场景生活化，不靠玄幻设定取胜。读者从假约会、重逢这类熟悉框架里进来，真正留下的是两个人如何重新学习诚实。",
        },
        "fullDescriptionZh": "一场婚礼周把旧关系重新推到灯光下。曾经用“假女友”互相挡过风的两个人，三年后再见面，发现表演留下的不是笑话，是没结算的感情。小说沿着筹备、亲友、旧地方打转，让亲密在众目睽睽里变得很难装。它不追求黑暗，追求那种明明知道规则、身体却先背叛规则的轻喜剧张力。",
        "recommendationZh": "在一堆2026年沉重新书旁边，它提供另一种阅读：清楚、好玩、仍对自尊认真。假约会是旧框架，作者把它写成“我们曾经多么需要一个安全的谎言”。适合想用英语读当代浪漫、又不想陷入过度 Melodrama 的人。",
        "audienceZh": "喜欢当代浪漫、假约会与重逢设定、想要轻松但不是空洞甜宠的读者。不适合寻找社会批判或黑暗爱情的人。",
    },
    {
        "matchTitle": "The Book of Chuck",
        "languageCode": "en",
        "chineseTitle": "查克之书",
        "publicationDate": "2026-01-01",
        "isbn13": "9780593854549",
        "publisher": "Tiny Reparations",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["家族", "南方", "奇幻边缘"],
        "coverImage": "/covers/book-of-chuck.jpg",
        "editorQuoteZh": "有人一碰就能看见死亡，家族却仍要过日子。",
        "readingMoodZh": "沉、热、带一点超自然的家族史诗。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Tiny Reparations / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026年英语文学新作，ISBN 与封面可核。",
        "author": {
            "name": "LaToya Watkins",
            "localizedName": "拉托娅·沃特金斯",
            "nationality": "美国",
            "biographyZh": "拉托娅·沃特金斯写得州与黑人家庭的内部天气。她的小说让超自然元素为伦理服务，而不是为惊吓服务。文字有重量，人物有自己的沉默。她关注的不是“奇事发生了”，而是奇事如何迫使一个家族重新分配爱与责任。",
        },
        "fullDescriptionZh": "得州一个家族里，有人带着过于锋利的感知活着——碰触会带出不该被提前知道的事。小说不把这写成超能力爽文，而写成负担：看见之后，还怎么做母亲、儿子、姐妹。时间在家庭饭桌、信仰和土地之间展开，秘密以照顾的形式保存。读者会被要求慢慢进入，而不是收集线索。",
        "recommendationZh": "它让“奇”服从于人。2026年英语新书里，这种把家族伦理写扎实的作品并不多。沃特金斯的句子有南方热度，却不炫技。想读文学多于类型、又能接受轻微超自然的人，会在这里找到今年少见的沉静。",
        "audienceZh": "读得动家族群像、不排斥轻微超自然、想要文学密度的读者。不适合寻求高概念科幻解释的人。",
    },
    {
        "matchTitle": "The Calamities",
        "languageCode": "en",
        "chineseTitle": "灾厄",
        "publicationDate": "2026-08-01",
        "isbn13": "9798217091812",
        "publisher": "Del Rey",
        "primaryGenre": "奇幻",
        "genres": ["奇幻"],
        "tags": ["暗黑奇幻", "家族", "当代"],
        "coverImage": "/covers/calamities.jpg",
        "editorQuoteZh": "这家人做灵魂买卖，账本比血更清楚。",
        "readingMoodZh": "脏金、喧闹、带着诅咒的家族传奇。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Del Rey / ISBN",
        "sourceUrl": "",
        "selectionReason": "2026年8月成人奇幻新作，ISBN 可核。",
        "author": {
            "name": "Chuck Wendig",
            "localizedName": "查克·温迪格",
            "nationality": "美国",
            "biographyZh": "查克·温迪格写得又快又密，类型横跨惊悚、奇幻与末日。句子带刺，幽默常从糟糕处境里冒出来。他喜欢把民间传说塞进当代美国的加油站和家庭饭局。读他要有心理准备：热闹，但不温柔。",
        },
        "fullDescriptionZh": "一个半人半魔的家族靠买卖灵魂起家。生意要规则，规则要有人守，也要有人破。小说把当代生活与黑暗交易叠在一起，让“家庭企业”变成字面意义。人物嘴贫，处境却狠。它不是田园奇幻，是把诅咒写成继承法的故事。",
        "recommendationZh": "想在2026年读一部吵闹、黑暗、又仍是家庭小说的奇幻，它很合适。温迪格不追求空灵，追求速度和口吻。恶不是抽象概念，是餐桌上的职业。适合能接受粗粝语言和道德脏边的读者。",
        "audienceZh": "喜欢当代暗黑奇幻、家族黑帮气质、以及对脏话和黑色幽默不敏感的读者。不适合清淡奇幻或儿童向幻想读者。",
    },
    {
        "matchTitle": "Immortal Rose",
        "languageCode": "en",
        "chineseTitle": "不朽玫瑰",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "HarperCollins",
        "primaryGenre": "奇幻",
        "genres": ["奇幻", "爱情"],
        "tags": ["浪漫奇幻", "香水", "代价"],
        "coverImage": "/covers/immortal-rose.jpg",
        "editorQuoteZh": "香味能封住魔法，交易却封不住后果。",
        "readingMoodZh": "香、密、带一点危险的华丽。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "HarperCollins listing; ISBN 待书店页复核",
        "sourceUrl": "",
        "selectionReason": "2026年成人奇幻新作，封面已有；ISBN 在目录中缺失，故标待核验。",
        "author": {
            "name": "Alexandra Bracken",
            "localizedName": "亚历山德拉·布拉肯",
            "nationality": "美国",
            "biographyZh": "亚历山德拉·布拉肯以青年与成人幻想知名，善于把能力、契约和情感绑在一起写。她的世界规则清楚，人物常被“选择的代价”推着走。读者会感到熟悉的浪漫奇幻骨架，但香水和魔法的组合让感官先于刀剑。",
        },
        "fullDescriptionZh": "香水里封着魔法，每一种气味都对应一种交易。想得到的人要付出，想逃离的人会发现香味比记忆更黏。故事沿着制作、交换与欲望展开，把嗅觉写成权力。它保留浪漫奇幻的吸引，也不断提醒：好闻的东西最会改写判断。",
        "recommendationZh": "在剑与龙之外，这是一部用感官建立世界的2026新书。规则简单，余味复杂。适合想从浪漫奇幻进入成人向、又希望设定有物质感的读者。华丽不是装饰，是情节的一部分。",
        "audienceZh": "浪漫奇幻读者、喜欢“魔法有代价”设定、以及对气味和工艺细节有耐心的人。不适合硬核史诗奇幻迷。",
    },
    {
        "matchTitle": "My Sister Is Going to Kill Me",
        "languageCode": "en",
        "chineseTitle": "我姐姐要杀了我",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "William Morrow",
        "primaryGenre": "推理",
        "genres": ["推理", "家庭"],
        "tags": ["姐妹", "户外", "家庭推理"],
        "coverImage": "/covers/sister-kill.jpg",
        "editorQuoteZh": "漂流可以是度假，也可以是不在场证明。",
        "readingMoodZh": "阳光明亮，水面下发紧。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "William Morrow listing; ISBN 待核",
        "sourceUrl": "",
        "selectionReason": "2026年家庭推理新书，封面已有；ISBN 缺失，标待核验。",
        "author": {
            "name": "Nina Simon",
            "localizedName": "尼娜·西蒙",
            "nationality": "美国",
            "biographyZh": "尼娜·西蒙近年以把博物馆、公共空间和叙事结合而为人注意，小说写作则把那种“如何让一群人共同经历一件事”的敏感带进家庭罪案。她写姐妹，不只写血缘亲密，也写竞争、照料和无法退出的共同历史。",
        },
        "fullDescriptionZh": "姐妹去大峡谷一带漂流，行程本该是修复关系的户外活动。水上的日子很具体：装备、节奏、谁负责怕。命案让“我们是一家人”变成证据问题。小说用旅行的明亮反衬家庭内部的旧裂痕，让读者一直分不清：危险来自河道，还是来自认识太久的那个人。",
        "recommendationZh": "标题像玩笑，内容却认真对待姐妹之间那种无法注销的关系。它比冷酷本格更生活，比纯家庭小说更有案件推进。2026年英语推理里，这是适合“想轻松进入、仍被伦理抓住”的一本。",
        "audienceZh": "想读家庭向推理、能接受户外场景、喜欢人物关系大于密室诡计的读者。不适合古典本格纯粹派。",
    },
    {
        "matchTitle": "Dear Debbie",
        "languageCode": "en",
        "chineseTitle": "亲爱的黛比",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Poisoned Pen",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "惊悚"],
        "tags": ["复仇", "心理悬疑"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "专栏里的建议，她决定先用在自己身上。",
        "readingMoodZh": "快、利、带着一点痛快的凉。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Poisoned Pen / 2026 fiction lists",
        "sourceUrl": "",
        "selectionReason": "2026年英语畅销向悬疑新书；ISBN 待书店复核。",
        "author": {
            "name": "Freida McFadden",
            "localizedName": "弗蕾达·麦克法登",
            "nationality": "美国",
            "biographyZh": "麦克法登是近年英语圈极高销量的悬疑作者，作品节奏快、章节短、反转密集。她当过医生，写封闭空间和不可靠叙述很顺手。文学圈未必把她当典范，读者却很清楚自己在买什么：晚上能一口气翻完的紧张感。",
        },
        "fullDescriptionZh": "人生专栏作家自己的生活崩了。她曾给陌生人写过许多听起来正确的建议，现在决定拿这些句子当行动手册。小说沿着“建议—执行—后果”推进，让自我帮助话语变得危险。它不追求细密社会分析，追求那种读着读着会笑、随即又不想笑的速度。",
        "recommendationZh": "作为2026年英语大众悬疑的代表样本，它说明这类书为什么仍被需要：痛快、好读、道德灰色。若你已读过她的女佣系列，会认出同一种推进力；若你第一次读，也能很快上车。不要期待余韵，期待当晚的心跳。",
        "audienceZh": "喜欢快节奏心理悬疑、good-for-her 复仇气质、以及睡前翻页的读者。不适合寻求长句文学或开放式余味的人。",
    },
    # ---------- Spanish ----------
    {
        "matchTitle": "Los Huérfanos",
        "languageCode": "es",
        "chineseTitle": "孤儿们",
        "publicationDate": "2026-09-09",
        "isbn13": "",
        "publisher": "Planeta",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "推理"],
        "tags": ["黑手党", "家族", "马贝拉"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "马贝拉的阳光很好，阴影里的家族更好。",
        "readingMoodZh": "热、暴、像犯罪编年史。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Planeta / RTVE 2026-09-09 coverage",
        "sourceUrl": "",
        "selectionReason": "2026年9月9日西班牙原版出版。",
        "author": {
            "name": "Carmen Mola",
            "localizedName": "卡门·莫拉",
            "nationality": "西班牙",
            "biographyZh": "卡门·莫拉是三人写作集体的笔名，以黑暗、高速的西班牙语犯罪小说知名。他们写暴力时不回避脏，也写家庭如何把恶变成日常管理。读者要能接受残酷场面；回报是结构清楚、人物欲望明确的当代西班牙黑色小说。",
        },
        "fullDescriptionZh": "三个从孤儿院活下来的人，把马贝拉的犯罪网络当成另一种亲属制度。对面是另一户人家，顶端还有不愿宽恕的姐姐。小说把腐败、移民资本和家族忠诚绞在一起，让阳光海岸变成权力地图。它不是侦探找真相那么简单，更像看一群人如何学习作恶，又如何被恶反过来命名。",
        "recommendationZh": "2026年西语新书里，这是大众犯罪小说的主菜：场面大，伦理脏，人物多。莫拉的签名仍在——速度、残忍、家庭。想用西班牙语读当代黑色、并能接受暴力描写的人，会感到这就是“今年为什么还在谈他们”。",
        "audienceZh": "西班牙语犯罪小说读者、能接受残酷与黑帮群像的人。不适合寻求温暖现实主义或清淡推理的读者。",
    },
    {
        "matchTitle": "La piel de una gota",
        "languageCode": "es",
        "chineseTitle": "一滴水的皮肤",
        "publicationDate": "2026-09-16",
        "isbn13": "",
        "publisher": "Destino",
        "primaryGenre": "推理",
        "genres": ["推理", "悬疑"],
        "tags": ["警察程序", "爆炸", "巴利亚多利德"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "城市被点亮的那一刻，有人把它当成靶子。",
        "readingMoodZh": "急促、城市、程序与恐慌并行。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Destino / author site 2026-09-16",
        "sourceUrl": "",
        "selectionReason": "2026年9月16日出版，探长系列回归。",
        "author": {
            "name": "César Pérez Gellida",
            "localizedName": "塞萨尔·佩雷斯·赫伊达",
            "nationality": "西班牙",
            "biographyZh": "赫伊达是西班牙语黑色小说的重要写手，以巴利亚多利德为文学首都，塑造过探长 Ramiro Sancho。他写罪案像写城市解剖：街道、仪式、职业习惯都在场。节奏快，但不牺牲警察工作的具体性。",
        },
        "fullDescriptionZh": "巴利亚多利德接连发生袭击，城市的节日灯光变成恐慌的布景。退役军人式的凶手按自己的逻辑行动，探长 Sancho 必须在私人生活与公共危机之间分配注意力。小说把地方写得很具体，让读者跟着调查穿过广场、程序和疲劳。爆炸是情节，城市才是真正持续的压力。",
        "recommendationZh": "系列角色回归往往只是情怀，这一本把情怀用在“我还认识这片街”上。2026年西语推理里，它提供少见的地方密度。喜欢警察程序、又不想读翻译腔北欧冷感的人，会觉得语感对了。",
        "audienceZh": "西班牙语警察小说读者、赫伊达旧作追随者、喜欢城市空间参与破案的人。不适合只想要乡村神秘学的读者。",
    },
    {
        "matchTitle": "Un hombre de honor",
        "languageCode": "es",
        "chineseTitle": "一个有荣誉的人",
        "publicationDate": "2026-09-30",
        "isbn13": "9788408326595",
        "publisher": "Planeta",
        "primaryGenre": "历史",
        "genres": ["历史", "爱情"],
        "tags": ["纽约", "一九六八", "家族"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "一九六八年的纽约，荣誉是一种昂贵的借口。",
        "readingMoodZh": "宽、热、历史通俗长篇的推进感。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Planeta ISBN 9788408326595",
        "sourceUrl": "",
        "selectionReason": "2026年9月30日出版，ISBN 可核。",
        "author": {
            "name": "Paloma Sánchez-Garnica",
            "localizedName": "帕洛玛·桑切斯-加尔尼卡",
            "nationality": "西班牙",
            "biographyZh": "桑切斯-加尔尼卡是西语大众历史小说的代表作者之一，写记忆、家族秘密与政治压力下的个人选择。她的书好读，情感明确，历史背景为人物服务。行星奖之后，她仍走这条“让更多人读完一段难历史”的路。",
        },
        "fullDescriptionZh": "一九六八年纽约。女记者想在男人主导的新闻界立足，警察走在哈莱姆与腐败的夹缝里，家族则把联姻当成秩序。越南、民权、黑手党传闻构成远景，近景仍是两个人如何在阶级里相爱、如何在调查里互相拖累。小说篇幅长，线索多，读感像连续剧，却始终绕着“什么叫荣誉”打转。",
        "recommendationZh": "它不是学术历史，是让历史变成命运感的通俗长篇。2026年西语新书里，这种面向广大读者的历史情感小说仍然有效。适合想用西班牙语读长故事、并接受浪漫与罪案并进的人。",
        "audienceZh": "大众历史小说读者、喜欢家族与时代交叉的人。不适合寻求实验叙事或极简风格的读者。",
    },
    {
        "matchTitle": "Comerás flores",
        "languageCode": "es",
        "chineseTitle": "你将吃花",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Libros del Asteroide",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "文学小说"],
        "tags": ["年龄差", "欲望", "当代西班牙"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "爱情若长在湿处，花也会有味道。",
        "readingMoodZh": "黏、暗、句子漂亮但不安慰人。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Libros del Asteroide / 2026 Spanish lists",
        "sourceUrl": "",
        "selectionReason": "2026年西班牙现象级新作；精确月份与ISBN待核。",
        "author": {
            "name": "Lucía Solla Sobral",
            "localizedName": "露西亚·索亚·索布拉尔",
            "nationality": "西班牙",
            "biographyZh": "索亚·索布拉尔是近年西班牙文坛被迅速看见的声音，写欲望时不把道德当装饰。她的句子有文学杂志的密度，故事却贴近当代关系里的权力差。读者会感到被美吸引，也被美警告。",
        },
        "fullDescriptionZh": "一段年龄悬殊的感情里，爱与利用很难分开。小说让“吃花”这种过美的意象落到身体和阶层上，使浪漫语言变得可疑。场景当代，心理却很旧：谁被看成风景，谁被看成胃。它不是谜题悬疑，是关系本身慢慢显出毒性。",
        "recommendationZh": "2026年西语新书里，它代表更年轻、更文学的那一路：不靠奖项口号，靠不舒服的准确。适合能接受欲望写得很具体、又不想读类型公式的人。美是诱饵，伦理是钩。",
        "audienceZh": "当代西语文学读者、对权力与亲密关系敏感的人。不适合寻找甜蜜爱情或明确凶手的读者。",
    },
    {
        "matchTitle": "Mentira",
        "languageCode": "es",
        "chineseTitle": "谎言",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Ediciones B",
        "primaryGenre": "推理",
        "genres": ["推理", "悬疑"],
        "tags": ["犯罪", "谎言", "畅销"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "标题已经坦白：谎言才是引擎。",
        "readingMoodZh": "快、滑、大众犯罪小说的推进。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Ediciones B / Sant Jordi 2026 lists",
        "sourceUrl": "",
        "selectionReason": "2026年圣乔治日西语热销新作；ISBN待核。",
        "author": {
            "name": "Juan Gómez-Jurado",
            "localizedName": "胡安·戈麦斯-胡拉多",
            "nationality": "西班牙",
            "biographyZh": "戈麦斯-胡拉多是西班牙当代最能把读者留在章节末尾的犯罪作家之一。他写得清楚、快、人物功能明确。文学上或许有人觉得太顺，但对想用西班牙语进入类型阅读的人，他几乎是一条宽路。",
        },
        "fullDescriptionZh": "谎言不是点缀，是结构。人物用假话保护自己，也用假话伤害别人，调查则必须在这些假话里找仍能承重的那一根。小说面向广大读者，节奏紧，场景切换利落。它不要求你做笔记，要求你愿意被带着跑。",
        "recommendationZh": "作为2026年西语畅销向犯罪小说，它完成了自己的工作：好读、有钩。若你想从流行作家进入西班牙语原版，这比先锋实验更友好。期待深度哲学的人会觉得它光滑，那也是它的诚实。",
        "audienceZh": "大众犯罪读者、戈麦斯-胡拉多旧作读者、想提高西语阅读流利度的类型爱好者。",
    },
    {
        "matchTitle": "La intriga del funeral inconveniente",
        "languageCode": "es",
        "chineseTitle": "一场不合时宜葬礼的阴谋",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Seix Barral",
        "primaryGenre": "推理",
        "genres": ["推理", "文学小说"],
        "tags": ["讽刺", "葬礼", "幽默"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "葬礼最怕准时，更怕有人认真。",
        "readingMoodZh": "讽、轻、智性的西班牙式玩笑。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Seix Barral / Sant Jordi 2026",
        "sourceUrl": "",
        "selectionReason": "2026年圣乔治日西语小说高销量新作。",
        "author": {
            "name": "Eduardo Mendoza",
            "localizedName": "爱德华多·门多萨",
            "nationality": "西班牙",
            "biographyZh": "门多萨是西班牙当代文学的重要幽默家，巴塞罗那在他笔下既庄严又荒唐。他能写严肃历史，也能写侦探笑话。读者会感到一种老派的聪明：不靠网络梗，靠人物如何在制度里出丑。",
        },
        "fullDescriptionZh": "一场不合时宜的葬礼变成阴谋的舞台。哀悼的礼仪、家族的体面、城市的旁观，全都可能是伪装。门多萨用讽刺把推理轻轻托起，让读者在笑的时候仍能跟上谁在撒谎。它不是黑暗暴力，是社会礼仪自己泄露的破绽。",
        "recommendationZh": "2026年还在写、还能让圣乔治日读者排队的门多萨，本身就说明一种持续的阅读口味：要聪明，也要好笑。适合把推理当社会喜剧来读的人。",
        "audienceZh": "喜欢文学幽默、巴塞罗那城市气味、以及轻推理的西语读者。不适合寻求血腥硬派的人。",
    },
    {
        "matchTitle": "La ciudad de las luces muertas",
        "languageCode": "es",
        "chineseTitle": "死灯之城",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Destino",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "历史"],
        "tags": ["纳达尔奖", "城市", "记忆"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "灯灭了，城市才开始被真正看见。",
        "readingMoodZh": "文学、意象浓、奖项向长篇。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Destino / Premio Nadal 2026 reports",
        "sourceUrl": "",
        "selectionReason": "2026纳达尔奖作品，当年出版。",
        "author": {
            "name": "David Uclés",
            "localizedName": "达维德·乌克莱斯",
            "nationality": "西班牙",
            "biographyZh": "乌克莱斯因纳达尔奖被更广泛的西语读者看见。他的写作偏向意象与城市记忆，而不是类型机关。关于作者生平的公开细节仍宜以书店勒口为准；可以确定的是，2026年的这本长篇被放在西班牙文学奖的主舞台上。",
        },
        "fullDescriptionZh": "一座与灯光、熄灭和记忆有关的城市被写成可走的空间。小说用文学语言处理公共历史与私人看见，让“灯”既是市政也是隐喻。它更适合慢慢读，而不是当谜题拆。奖项带来注意力，真正留下的是句子如何给黑暗命名。",
        "recommendationZh": "在畅销犯罪旁边，需要一本代表2026年西班牙文学奖路径的书。它提醒原版阅读不只是类型。想用西班牙语接触当代纯文学、并能接受意象大于情节的人，可以从这里进。",
        "audienceZh": "文学奖读者、喜欢城市隐喻与较慢节奏的人。不适合只找强情节的读者。",
    },
    {
        "matchTitle": "Han cantado bingo",
        "languageCode": "es",
        "chineseTitle": "他们唱了宾果",
        "publicationDate": "2026-05-01",
        "isbn13": "",
        "publisher": "Reservoir Books",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "成长"],
        "tags": ["岛屿", "姐妹", "兰萨罗特"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "宾果唱响之前，两姐妹已经把火山当成秘密。",
        "readingMoodZh": "岛风、碎片、成长的咸味。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Reservoir Books / RTVE 2026-05",
        "sourceUrl": "",
        "selectionReason": "2026年出道长篇，媒体与书店可核。",
        "author": {
            "name": "Lana Corujo",
            "localizedName": "拉娜·科鲁霍",
            "nationality": "西班牙",
            "biographyZh": "拉娜·科鲁霍来自兰萨罗特，先以插画为人所知，后把岛屿从旅游明信片里夺回来写成小说。她写家乡不美化，也不控诉到底。读者会感到一种自己人的含混：爱这个地方，又知道它如何保存伤害。",
        },
        "fullDescriptionZh": "两姐妹在祖母去宾果的间隙跑向一座虚构火山，数到三再跑回来。一个夜晚规则变了，此后人生像一张十五格的宾果卡被逐格填上。小说用碎片和年龄跳切写家庭、内疚与岛的内部天气。火山不在地图上，却比景点更真。",
        "recommendationZh": "2026年西语圈的网络与书店同时看见它，不是因为类型公式，而是因为岛屿被写成秘密。结构巧，情感准。适合想读成长、地方和姐妹，又不想要标准青春疼痛模板的人。",
        "audienceZh": "当代文学读者、对岛屿与家庭记忆感兴趣的人。不适合寻找线性强情节的读者。",
    },
    # ---------- Japanese ----------
    {
        "matchTitle": "ゾンビ回収婦",
        "languageCode": "ja",
        "chineseTitle": "僵尸回收妇",
        "publicationDate": "2026-07-09",
        "isbn13": "9784065441121",
        "publisher": "講談社",
        "primaryGenre": "科幻",
        "genres": ["科幻", "文学小说"],
        "tags": ["芥川奖", "AI", "劳动"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "世界被收拾干净之前，先被劳动定义。",
        "readingMoodZh": "冷、短、荒诞里的认真。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Kodansha book page, ISBN 9784065441121",
        "sourceUrl": "",
        "selectionReason": "第175回芥川奖作品，2026年7月9日单行本。",
        "author": {
            "name": "小砂川チト",
            "localizedName": "小砂川千人",
            "nationality": "日本",
            "biographyZh": "小砂川チト一九九〇年生于岩手，从群像新人文学奖走入文坛，多次进入芥川奖候选后于二〇二六年以本作获奖。她写虚构世界时仍抓住劳动、家庭与“好孩子”如何被系统征用。文字干净，想像却不安慰人。",
        },
        "fullDescriptionZh": "AI侵蚀之后，酒店里只剩一名清扫妇。她的工作是拾起被杀死的僵尸骸骨，让世界看起来仍然美丽。现实会裂开另一层，三十多年当好孩子的惯性却还在。小说短，设定浓，把科幻劳动写成一种几乎宗教的认真。读完更像被提醒：有人负责把可怕的东西收走，赞美很少到来。",
        "recommendationZh": "2026年上半年日本纯文学最被看见的一本。它证明短篇体量也能撑起世界设定，而且不把奖项写成正确答案。想用日语读当代文学、又能接受怪异科幻外壳的人，应从这里开始今年的新书。",
        "audienceZh": "日语纯文学读者、对劳动与AI主题感兴趣、能接受短而密文本的人。不适合寻求长篇世界志的奇幻读者。",
    },
    {
        "matchTitle": "けんぐゎい",
        "languageCode": "ja",
        "chineseTitle": "圈外",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "光文社",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["直木奖", "时代小说", "江户"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "圈外的人并非没有故事，只是信号到不了。",
        "readingMoodZh": "时代、痛、却有体温的长篇。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "第175回直木奖 / Kobunsha",
        "sourceUrl": "",
        "selectionReason": "第175回直木奖获奖作，2026年上半年刊行。",
        "author": {
            "name": "朝倉かすみ",
            "localizedName": "朝仓霞",
            "nationality": "日本",
            "biographyZh": "朝仓かすみ写人物的偏差与生活的不按计划。她并非只写时代，更写被制度放在外面的人如何仍要活。直木奖把她推到更大的读者面前，但她的核心仍是：不漂亮的人生也可以被认真书写。",
        },
        "fullDescriptionZh": "江户。脸上留着病痕的ふゆ与容貌被看成资本的妹妹，在父死后走进不同的劳动。性暴力、收养、医者与“真正的你”这类句子把ふゆ从圈外拖向另一种被看见。小说用时代外壳写当代仍在的歧视：谁被允许出现在信号范围内。情感强，但不把苦难写成景观。",
        "recommendationZh": "2026年娱乐小说最高奖给了一部关于“圈外”的时代之作，这本身值得停一下。它让时代小说不只是刀与忠义。想读日语长篇、关心边缘人物、又能接受沉重的人，会感到奖项这次没有走最轻的路。",
        "audienceZh": "时代小说读者、直木奖关注者、对性别与残疾议题有准备的人。不适合轻松时代冒险爱好者。",
    },
    {
        "matchTitle": "きずもの",
        "languageCode": "ja",
        "chineseTitle": "伤物",
        "publicationDate": "2026-09-30",
        "isbn13": "9784093867887",
        "publisher": "小学館",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["友情", "时间", "北海道报纸连载"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "伤还在，人却被允许再爱一点自己。",
        "readingMoodZh": "长、暖中带刺、新闻连载改成的厚书。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Shogakukan ISBN 9784093867887",
        "sourceUrl": "",
        "selectionReason": "2026年9月30日刊行，ISBN可核。",
        "author": {
            "name": "西加奈子",
            "localizedName": "西加奈子",
            "nationality": "日本",
            "biographyZh": "西加奈子以《サラバ！》获直木奖，也写过病中非虚构。她的小说口语热、感情直接，却不浅。读者常感到被作者拉着手走路：世界很硬，句子却肯陪你。五年长篇对她是一次把旧友情与新生活放在同一张桌子上的努力。",
        },
        "fullDescriptionZh": "小说家与幼驯染在SNS上维持一种不近不远。另一边，女人因某事离开日本，去温哥华与友人合住。两对旧识各自被时间改写。书从报纸连载改成单行本，篇幅长，允许生活的琐碎进来。伤不是一次事件，是持续的自我相处。",
        "recommendationZh": "2026年秋季日语长篇里，这是少数能同时交给文学读者和更广大读者的书。西加奈子的声音辨识度高：疼，但不表演绝望。适合想用日语读当代生活、并接受篇幅的人。",
        "audienceZh": "西加奈子读者、日语长篇读者、对友情与移居生活感兴趣的人。不适合只想要强情节的人。",
    },
    {
        "matchTitle": "永遠の記憶",
        "languageCode": "ja",
        "chineseTitle": "永远的记忆",
        "publicationDate": "2026-08-05",
        "isbn13": "",
        "publisher": "文藝春秋",
        "primaryGenre": "推理",
        "genres": ["推理"],
        "tags": ["伽利略", "汤川学", "系列"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "有些谜不能忘，忘了人就不完整。",
        "readingMoodZh": "本格、系列情感、夏季长篇。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Bungeishunju Galileo series, 2026-08-05",
        "sourceUrl": "",
        "selectionReason": "伽利略系列2026年8月5日最新长篇。",
        "author": {
            "name": "東野圭吾",
            "localizedName": "东野圭吾",
            "nationality": "日本",
            "biographyZh": "东野圭吾是日语推理最被翻译、也被最广泛阅读的作者之一。伽利略系列以物理学者汤川学的冷静对照警察的现场。他能写温情，也能写很冷的诡计。读者不必先成为本格信徒，也能被带着走完一座谜。",
        },
        "fullDescriptionZh": "内海被刺，老人沉默，年轻女人进入视线。汤川与草薙从一件遗物走进“不能忘记的谜”。系列读者会感到熟悉的对照：科学解释与人情债并行。它对未读过前作的人仍可进入，但对内海的关心会因旧识而更深。谜是钩，记忆才是题。",
        "recommendationZh": "2026年日语大众阅读几乎无法绕开的一本。它不是实验，是系列承诺的兑现。想用日语读流畅推理、或完成伽利略地图的人，这就是今年的主页。",
        "audienceZh": "东野读者、伽利略系列追随者、日语推理入门者。不适合寻求纯文学实验的人。",
    },
    {
        "matchTitle": "ファイア・ドーム 上",
        "languageCode": "ja",
        "chineseTitle": "火焰穹顶 上",
        "publicationDate": "2026-06-05",
        "isbn13": "9784093867696",
        "publisher": "小学館",
        "primaryGenre": "推理",
        "genres": ["推理", "社会议题"],
        "tags": ["谣言", "媒体", "地方都市"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "谣言是轻薄的娱乐，烧到人身上却很重。",
        "readingMoodZh": "厚、社会派、上下卷的第一口气。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Shogakukan ISBN 9784093867696",
        "sourceUrl": "",
        "selectionReason": "2026年6月5日刊行，ISBN可核。",
        "author": {
            "name": "辻村深月",
            "localizedName": "辻村深月",
            "nationality": "日本",
            "biographyZh": "辻村深月从梅菲斯特奖出道，写过青春、家庭与社会事件如何吞噬普通人。《かがみの孤城》之后，她拥有极广的读者。这部上下卷是出道二十二年的长篇，把“人们为什么喜欢看别人的灾难”写成可燃物。",
        },
        "fullDescriptionZh": "二十五年前，地方都市因百货店接待员绑架杀人被报道点燃。谣言烧向加害者，也烧向受害者。看似冷却的城镇里，旧因缘召来新事件。上卷把火的结构架好：媒体、邻里、家庭如何互相加油。它要求你准备读下卷，而不是把上卷当完整甜点。",
        "recommendationZh": "2026年日语社会派推理的大部头。辻村把“看客”写成情节引擎，比单纯找凶手更让人坐立不安。愿意读厚书、关心舆论伤害的人，会觉得这是今年该给时间的作品。",
        "audienceZh": "社会派推理读者、辻村深月读者、能接受上下卷的人。不适合只想读单行本薄推理的人。",
    },
    {
        "matchTitle": "探偵小石は戻らない",
        "languageCode": "ja",
        "chineseTitle": "侦探小石不再回来",
        "publicationDate": "2026-09-30",
        "isbn13": "9784093868051",
        "publisher": "小学館",
        "primaryGenre": "推理",
        "genres": ["推理"],
        "tags": ["系列", "逆转", "福冈"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "助手看见的不是名侦探，是站在犯人位置的人。",
        "readingMoodZh": "轻快对白下的本格恶作剧。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Shogakukan ISBN 9784093868051",
        "sourceUrl": "",
        "selectionReason": "2026年9月30日系列续作。",
        "author": {
            "name": "森バジル",
            "localizedName": "森巴吉尔",
            "nationality": "日本",
            "biographyZh": "森バジル以松本清张奖出道，凭《侦探小石不恋爱》成为2025–2026年书店推理热点。他写侦探迷自己当侦探的快乐与错位，对白有趣，结构却认真骗人。续作把“还能不能相信这个人”变成新的阅读契约。",
        },
        "fullDescriptionZh": "恋案专家小石与助手莲杖继续调查，直到莲杖看见小石站在犯人那一侧。系列第一作靠逆转口碑传开，第二作必须面对“读者已经有防备”。小说仍用轻快的侦探事务所日常作外壳，内核是信任如何被案件改写。读前作会更爽，不读也能感到不对劲。",
        "recommendationZh": "2026年秋季日语推理的话题续作。它证明畅销可以来自结构乐趣，而不只来自残酷。喜欢被骗得开心、又想用日语读当代本格的人，这是明确选项。",
        "audienceZh": "本格爱好者、系列读者、喜欢侦探与助手对手戏的人。不适合厌恶被叙述捉弄的读者。",
    },
    {
        "matchTitle": "変な地図",
        "languageCode": "ja",
        "chineseTitle": "奇怪的地图",
        "publicationDate": "2025-10-31",
        "isbn13": "9784575248104",
        "publisher": "双葉社",
        "primaryGenre": "悬疑",
        "genres": ["悬疑"],
        "tags": ["解谜", "地图", "视觉"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "先看图，再决定怕什么。",
        "readingMoodZh": "游戏感、视觉、阅读像探险。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "双葉社公式 / ISBN 9784575248104，2025-10-31刊（近12个月内）",
        "sourceUrl": "",
        "selectionReason": "雨穴「変な」系列近作；书店初版2025-10-31，ISBN可核。",
        "author": {
            "name": "雨穴",
            "localizedName": "雨穴",
            "nationality": "日本",
            "biographyZh": "雨穴以间取图和“奇怪的房子”系列打开一种视觉推理阅读。读者不是只被文字推着走，而是被迫看平面图。这种写法让解谜变成身体动作：你要盯、要对照、要承认自己看漏了。",
        },
        "fullDescriptionZh": "地图与小说组成一次阅读冒险。主角带着前作气质进入新的图形空间，文字负责气氛，图像负责陷阱。它邀请你把书转过来看，而不是快速滑过对话。适合愿意把阅读当解谜活动的人。",
        "recommendationZh": "2026年日语畅销里，它延续了雨穴把“看”写成情节的方法。不想只靠文字推理的人会觉得新鲜。它不是纯文学，是一种被证明有效的阅读玩具，而且玩具里仍有怕。",
        "audienceZh": "解谜爱好者、视觉推理读者、雨穴前作读者。不适合排斥插图与互动阅读的人。",
    },
    {
        "matchTitle": "多類婚姻譚",
        "languageCode": "ja",
        "chineseTitle": "多类婚姻谭",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "講談社",
        "primaryGenre": "爱情",
        "genres": ["爱情", "文学小说"],
        "tags": ["婚姻", "直木候选", "当代"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "结婚若这么难，小说就应该把难写清楚。",
        "readingMoodZh": "认真、对话多、当代伦理。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Kodansha / 第175回直木奖候选",
        "sourceUrl": "",
        "selectionReason": "2026年上半年直木奖候选长篇。",
        "author": {
            "name": "凪良ゆう",
            "localizedName": "凪良悠",
            "nationality": "日本",
            "biographyZh": "凪良ゆう以《流浪の月》《汝、星のごとく》成为近年日语大众文学的重要作者。她写亲密关系里的误解、性向与自尊，文字好读，伦理不省事。读者常在温柔里撞上无法和解的现实。",
        },
        "fullDescriptionZh": "几组婚姻与准婚姻被放在同一本书里：家庭期待、金钱、性向、世代。入籍前夜的对话变成战场，也变成唯一还能互相看见的地方。小说不给统一答案，给许多具体的卡住。当代日本婚姻的困难被写成可阅读的场景，而不是社论。",
        "recommendationZh": "2026年直木候选里，这是最贴近“现在的亲密如何失败”的一本。凪良的读者会认出那种又软又硬的语调。想用日语读爱情却不想要幻觉结局的人，应该读它。",
        "audienceZh": "凪良ゆう读者、关心婚姻与性别议题、喜欢人物对话的人。不适合寻求甜宠的人。",
    },
    # ---------- Korean ----------
    {
        "matchTitle": "아코디언",
        "languageCode": "ko",
        "chineseTitle": "手风琴",
        "publicationDate": "2026-06-22",
        "isbn13": "9788936439965",
        "publisher": "창비",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "成长"],
        "tags": ["成长", "现实", "长篇"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "十年后再响的那架琴，先经过现实。",
        "readingMoodZh": "沉、吸力强、成长小说的宽河。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Changbi ISBN 9788936439965",
        "sourceUrl": "",
        "selectionReason": "2026年6月22日出版，ISBN可核。",
        "author": {
            "name": "천명관",
            "localizedName": "千明官",
            "nationality": "韩国",
            "biographyZh": "千明官以强叙事和粗粝幽默写韩国现代的欲望与失败，《鲸》让他被更广泛的世界看见。他十年后再写长篇，仍抓住少年如何撞上严酷现实。句子有体力，人物不被保护，读者却很难放手。",
        },
        "fullDescriptionZh": "一个面对严酷现实的少年，在成长里学习什么可以发出声音，什么必须被按下去。手风琴是器物，也是节奏：伸展、挤压、漏风。小说走千明官熟悉的吸力——故事往前冲，社会却在每个弯道收费。它不是抒情少年，是把成长写成劳动与运气的小说。",
        "recommendationZh": "2026年韩语长篇最被期待的回归之一。读它像重新确认：通俗的推进力和文学的残酷可以是同一件事。想用韩语读“能一口气翻、翻完心里发沉”的人，这就是主菜。",
        "audienceZh": "千明官读者、韩语长篇读者、能接受粗粝成长叙事的人。不适合寻找清淡治愈的读者。",
    },
    {
        "matchTitle": "시간의 감촉",
        "languageCode": "ko",
        "chineseTitle": "时间的触感",
        "publicationDate": "2026-06-22",
        "isbn13": "9791141617226",
        "publisher": "문학동네",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["老年", "姐妹", "时间三部曲"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "六十岁以后，时间开始有皮肤。",
        "readingMoodZh": "慢、准、身体记忆的文学。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Aladin / Kyobo ISBN 9791141617226",
        "sourceUrl": "",
        "selectionReason": "2026年6月22日文学村刊行，纸书ISBN可核。",
        "author": {
            "name": "은희경",
            "localizedName": "殷熙耕",
            "nationality": "韩国",
            "biographyZh": "殷熙耕从《鸟的礼物》起就写人如何被自己的时间塑造。她不靠大事件，靠感觉的精度。七年来的这部长篇把六十岁姐妹放在同一视野里，完成她所说的时间三部曲。读她需要安静，不需要刺激。",
        },
        "fullDescriptionZh": "性格与外貌都不同的六十岁姐妹，把分开活过的岁月重新碰在一起。误解是旧的，身体是新的，老年仍有“第一次”。小说拒绝用情节高潮代替生活变化。时间在这里不是主题词，是触感：如何被触摸，如何被记错。",
        "recommendationZh": "2026年韩语文学里，这是把“老”写成仍可开始的少见作品。它不煽情，准确。适合已经读过殷熙耕、或愿意把阅读速度降下来的人。奖项喧哗之外，它提供真正的成年。",
        "audienceZh": "韩语纯文学读者、关心老年与姐妹关系的人。不适合寻求强情节或类型快感的读者。",
    },
    {
        "matchTitle": "찌니주의보",
        "languageCode": "ko",
        "chineseTitle": "蕾丝注意报",
        "publicationDate": "2026-09-01",
        "isbn13": "",
        "publisher": "창비",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "社会议题"],
        "tags": ["乡村", "酷儿", "邻里"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "偏见先到饭桌，理解有时也从饭桌来。",
        "readingMoodZh": "人间、对话、山村的慢热。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Changbi / Maeil Business 2026-09",
        "sourceUrl": "",
        "selectionReason": "2026年9月前后刊行，书评可核。",
        "author": {
            "name": "정지아",
            "localizedName": "郑芝雅",
            "nationality": "韩国",
            "biographyZh": "郑芝雅写全罗道土地上的人与历史余波，《父亲的解放日记》让更多读者认识她。新作把舞台换成高龄山村，写一对女性伴侣归乡后激起的好奇与敌意。她的力量在于不把人写成口号，而写成会一起吃饭的邻居。",
        },
        "fullDescriptionZh": "平均年龄七十八岁的水平村里，三十多岁的成珍与惠珍到来。当她们是女同志这件事传开，有人要赶，有人护，有人只是多看两眼。故事不靠大冲突升级，靠闲话、饭桌和慢慢改变的距离。少数者不是抽象词，是隔壁开始被议论的人。",
        "recommendationZh": "2026年韩语长篇里，这是把酷儿生活放进乡村伦理的重要作品。它温和，但不和稀泥。想读社会议题、又不想读宣言体的人，会感激这种饭桌现实主义。",
        "audienceZh": "韩语文学读者、关心乡村与性少数议题的人。不适合寻求都市快节奏的读者。",
    },
    {
        "matchTitle": "서리꽃",
        "languageCode": "ko",
        "chineseTitle": "霜花",
        "publicationDate": "2026-08-24",
        "isbn13": "9791167141644",
        "publisher": "해냄출판사",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["大河", "赵廷来"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "霜落在花上，历史仍要人去走。",
        "readingMoodZh": "大、传统、国民作家的长河。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "해냄 서리꽃 1권 ISBN 9791167141644",
        "sourceUrl": "",
        "selectionReason": "赵廷来2026年8月24日刊行，第1卷ISBN可核。",
        "author": {
            "name": "조정래",
            "localizedName": "赵廷来",
            "nationality": "韩国",
            "biographyZh": "赵廷来以《太白山脉》《阿里郎》《汉江》构成韩国读者心中的近代史地图。他写得长，写人群，写土地如何被政治撕开。新作仍会把个人放进历史的天气里。读他需要时间，也需要接受一种正统的史诗口气。",
        },
        "fullDescriptionZh": "霜花这个标题把易逝与坚硬放在一起。小说走赵廷来熟悉的路：人在历史里选择，选择又被更大的力量修改。它不是轻盈的2026都市小说，是国民作家再次要求读者坐下来面对时间。细节以书店勒口为准，阅读契约很明确——你要进入一条河，不是一个池塘。",
        "recommendationZh": "在年轻作者爆发的2026年，仍需要看见这种“长历史还在写”的书。它代表韩语阅读的另一根脊柱。适合已经读过赵廷来、或想理解韩国大河小说传统如何延续的人。",
        "audienceZh": "大河小说读者、韩国近代史爱好者。不适合寻找短平快的人。",
    },
    {
        "matchTitle": "절창",
        "languageCode": "ko",
        "chineseTitle": "绝唱",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "위즈덤하우스",
        "primaryGenre": "悬疑",
        "genres": ["悬疑", "文学小说"],
        "tags": ["具竝模", "声音", "黑暗"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "绝唱不是赞美，是把声音用到尽头。",
        "readingMoodZh": "暗、准、文学恐怖的边缘。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Wisdom House / 2026 lists",
        "sourceUrl": "",
        "selectionReason": "具竝模2026年新作，畅销榜可见；ISBN待核。",
        "author": {
            "name": "구병모",
            "localizedName": "具竝模",
            "nationality": "韩国",
            "biographyZh": "具竝模写少年、制度与身体的极限，文字冷而精确。她能把青春写成惊悚，把惊悚写成伦理问题。读者不要期待被安慰；期待被看穿。2026年新作延续她把“好听/好看”拆开审视的习惯。",
        },
        "fullDescriptionZh": "绝唱暗示一种把声音或生命用到边缘的状态。小说沿具竝模一贯的黑暗青春与制度压力展开，让美丽的词变得不安全。具体情节以原书为准，这里只标出阅读方向：不是励志，是把极限处境写清楚。短句、强压、道德含混。",
        "recommendationZh": "2026年韩语类型与文学交界处，具竝模仍是最稳的黑暗指南。适合已经信任她、或能接受不适感的读者。它不会为了畅销把刀收起来。",
        "audienceZh": "具竝模读者、文学惊悚读者、能接受沉重青春的人。不适合轻松向读者。",
    },
    {
        "matchTitle": "한국사 이상현상 연구원",
        "languageCode": "ko",
        "chineseTitle": "韩国史异常现象研究院",
        "publicationDate": "2026-08-31",
        "isbn13": "9791124137635",
        "publisher": "다이브",
        "primaryGenre": "科幻",
        "genres": ["科幻", "奇幻"],
        "tags": ["历史异常", "类型", "网文出身"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "历史若出现异常，研究院比教科书先上班。",
        "readingMoodZh": "巧、类型、知识游戏。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Aladin / Kyobo ISBN 9791124137635，다이브 2026-08-31",
        "sourceUrl": "",
        "selectionReason": "2026年8月31日刊行，ISBN可核。",
        "author": {
            "name": "최인서",
            "localizedName": "崔仁叙",
            "nationality": "韩国",
            "biographyZh": "崔仁叙从网络类型写作进入纸书市场，擅长把历史知识改写成异常现象。这种作者路径在2026年的韩国很典型：先有读者，再有装帧。文笔服务设定，设定服务阅读快感。",
        },
        "fullDescriptionZh": "韩国史里出现不该出现的现象，有一个机构负责研究、处理、也许还负责保密。小说用类型引擎带动历史知识，让读者在“原来如此”和“不可能吧”之间切换。它不是学院论文，是把民族史变成奇幻职场的阅读发明。",
        "recommendationZh": "2026年韩语大众阅读的另一极：不是纯文学，是设定带来的快乐。想用韩语读类型、并对韩国史有基本兴趣的人，会觉得这比教科书好玩，也比一般奇幻更本地。",
        "audienceZh": "类型读者、韩国史爱好者、网文转纸书的受众。不适合寻求纯文学句质的人。",
    },
    {
        "matchTitle": "인비인",
        "languageCode": "ko",
        "chineseTitle": "隐形人",
        "publicationDate": "2026-06-19",
        "isbn13": "9791172134297",
        "publisher": "한겨레출판",
        "primaryGenre": "惊悚",
        "genres": ["惊悚", "文学小说"],
        "tags": ["奇谭", "短篇", "成海娜"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "看不见的人，往往最先被消费。",
        "readingMoodZh": "短、凉、九个故事的鬼气。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Aladin / Kyobo ISBN 9791172134297",
        "sourceUrl": "",
        "selectionReason": "2026年6月19日刊行的第一本奇谭集，ISBN可核。",
        "author": {
            "name": "성해나",
            "localizedName": "成海娜",
            "nationality": "韩国",
            "biographyZh": "成海娜近年因小说集《混モノ》被热烈讨论，文字冷、准、对真假边界敏感。这本奇谭集把她推向更明确的类型外壳，九篇按昨天今天明天分辑。她仍不是为吓人而吓人，而是让当代无心成为一种更可怕的东西。",
        },
        "fullDescriptionZh": "九个奇谭分成昨日、今日、明日。有人消失，有人旁观，有人把别人的灾难当电影。短篇要求你迅速进入规则，再被规则翻面。隐形不是超能力，是社会选择不看。读完更像被提醒：无心比恶意更常见。",
        "recommendationZh": "2026年韩语短篇里，这是把文学读者和恐怖读者拉到同一张桌子上的书。成海娜的句子配得上奇谭这个旧词。适合喜欢短而准、能接受凉意的人。",
        "audienceZh": "短篇读者、文学恐怖读者、成海娜前作读者。不适合只想读长篇线性故事的人。",
    },
    {
        "matchTitle": "테니스 나무",
        "languageCode": "ko",
        "chineseTitle": "网球树",
        "publicationDate": "2026-09-04",
        "isbn13": "9791141603618",
        "publisher": "문학동네",
        "primaryGenre": "推理",
        "genres": ["推理", "文学小说"],
        "tags": ["达格奖", "尹高银"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "树还在，球的落点已经改了。",
        "readingMoodZh": "冷、准、犯罪与日常的缝。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "문학동네 ISBN 9791141603618",
        "sourceUrl": "",
        "selectionReason": "2026年9月4日刊行，ISBN可核。",
        "author": {
            "name": "윤고은",
            "localizedName": "尹高银",
            "nationality": "韩国",
            "biographyZh": "尹高银是少有获得英国犯罪作家协会达格奖的韩国作者，写罪案时保持文学的侧面。她让异常长在日常里，而不是从天而降。新长篇继续这种“看起来像生活，读着读着不对”的方法。",
        },
        "fullDescriptionZh": "网球与树构成一个看似休闲的意象，小说却把它放进犯罪与观察的结构里。尹高银不会把所有机关提前喊出来，她让你先接受一个普通世界。具体案情以原书为准；阅读体验可预期：冷静、有距离、突然意识到规则变了。",
        "recommendationZh": "2026年韩语推理里，这是更文学的一条。得过达格奖不保证每本都同样锋利，但作者的方法是稳定的。适合想用韩语读“不像推理的推理”的人。",
        "audienceZh": "文学推理读者、尹高银读者。不适合寻求高速反转的大众惊悚读者。",
    },
    # ---------- French ----------
    {
        "matchTitle": "Le Crime du paradis",
        "languageCode": "fr",
        "chineseTitle": "天堂里的罪",
        "publicationDate": "2026-03-03",
        "isbn13": "9782702192979",
        "publisher": "Calmann-Lévy",
        "primaryGenre": "推理",
        "genres": ["推理", "悬疑"],
        "tags": ["谁是凶手", "蓝色海岸", "1928"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "天堂别墅里，人人都像嫌疑犯。",
        "readingMoodZh": "封闭、阳光、旧式解谜的快乐。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Calmann-Lévy / ISBN 9782702192979",
        "sourceUrl": "",
        "selectionReason": "2026年3月3日出版，ISBN可核。",
        "author": {
            "name": "Guillaume Musso",
            "localizedName": "纪尧姆·穆索",
            "nationality": "法国",
            "biographyZh": "穆索是法国二十年来持续占据畅销榜的小说家，写悬念像写度假：阳光、秘密、最后的翻面。文学批评未必捧他，读者却很稳定。第23部长篇向阿加莎·克里斯蒂致敬，说明他清楚自己的契约——让人在封闭空间里玩谁是凶手。",
        },
        "fullDescriptionZh": "一九二八年安提布角。美国富豪夫妇的别墅里，三岁男孩失踪。世界围观，警察撞上谎言墙，年轻女作家 Agatha Harding 想把悲剧写成畅销书。小说用地中海的光去包一层 Christie 式解谜，让每个宾客都可能有动机。它追求阅读快感，不追求新形式。",
        "recommendationZh": "2026年法语大众阅读的中心样本。想用原版法语读流畅悬疑，这比先锋小说更像门。承认它是娱乐，反而能公正评价：结构清楚，气氛足，适合把法语读顺。",
        "audienceZh": "法语悬疑入门者、穆索读者、喜欢封闭别墅解谜的人。不适合寻求纯文学实验的读者。",
    },
    {
        "matchTitle": "L'Adolescence du perroquet",
        "languageCode": "fr",
        "chineseTitle": "鹦鹉的青春期",
        "publicationDate": "2026-08-19",
        "isbn13": "9782226513045",
        "publisher": "Albin Michel",
        "primaryGenre": "文学小说",
        "genres": ["文学小说"],
        "tags": ["寓言", "诺东", "秋季"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "爱不是应得的，鹦鹉比人先把这点说出来。",
        "readingMoodZh": "短、讽、诺东式寓言。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Albin Michel ISBN 9782226513045",
        "sourceUrl": "",
        "selectionReason": "2026年8月19日秋季例行新作。",
        "author": {
            "name": "Amélie Nothomb",
            "localizedName": "阿梅丽·诺冬",
            "nationality": "比利时",
            "biographyZh": "诺冬每年秋季交出一本短长篇，已成法语出版日历的一部分。她写极端关系、自尊与可笑的严肃。句子短，立场鲜明。近作偏自传后，这一本回到虚构寓言：人与鹦鹉的支配，像一份刻薄的家庭剧。",
        },
        "fullDescriptionZh": "电台评论员阿尔邦收养一只非洲灰鹦鹉。喂养变成亲职，亲职变成暴政，公寓变成青春期的战场。小说短， varié 的玩笑和突然的狠并置。它讨论爱是否被亏欠，却用一只会说话的鸟来把人逼到滑稽。读完像听完一则过长的寓言，寓意并不温柔。",
        "recommendationZh": "2026年法语秋季无法绕开的签名。喜欢诺冬的人会找到熟悉的锋利；不喜欢的人也知道自己在反对什么。作为短篇体量的原版阅读，它很适合保持法语的季候感。",
        "audienceZh": "诺冬读者、喜欢短长篇与寓言的法语读者。不适合寻求厚重现实主义的人。",
    },
    {
        "matchTitle": "Fauves",
        "languageCode": "fr",
        "chineseTitle": "猛兽",
        "publicationDate": "2026-01-07",
        "isbn13": "",
        "publisher": "Albin Michel",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "历史"],
        "tags": ["马戏团", "八〇年代", "成长"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "驯狮之前，先要承认自己也是兽。",
        "readingMoodZh": "汗、血、帐篷里的光与暗。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Albin Michel / Le Figaro 2026-01",
        "sourceUrl": "",
        "selectionReason": "2026年1月7日出版。",
        "author": {
            "name": "Mélissa Da Costa",
            "localizedName": "梅丽莎·达科斯塔",
            "nationality": "法国",
            "biographyZh": "达科斯塔是近年来法国最被阅读的小说家之一，能在情感通俗与更硬的题材之间切换。她拥有极大的读者信任。这一本把舞台换成一九八〇年代的巡回马戏团，让男性气质、暴力与光斑同场。她仍写得清楚，却更脏。",
        },
        "fullDescriptionZh": "十七岁的托尼与父亲冲突后进入巡回马戏团，从杂务做到面对狮子与豹。帐篷亮时是童话，灯灭后是父权、汗和血。小说用兽类对照人如何证明自己是男人。时代选在猛兽表演尚未从马戏团消失的年代，让危险是职业，不是隐喻游戏。",
        "recommendationZh": "2026年开年法语大众文学的重要一本。它说明畅销作者不必重复同一碗汤。想用原版法语读好读的长篇、又能接受粗粝成长的人，会感到今年从一月就开始了。",
        "audienceZh": "达科斯塔读者、喜欢成长与职业世界的人。不适合排斥动物表演题材或粗粝描写的读者。",
    },
    {
        "matchTitle": "C'était ça ou mourir",
        "languageCode": "fr",
        "chineseTitle": "要么这样要么死",
        "publicationDate": "2026-08-01",
        "isbn13": "",
        "publisher": "Grasset",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "悬疑"],
        "tags": ["龚古尔初选", "秋季"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "标题已经把选择压缩成一口气。",
        "readingMoodZh": "紧、当代、奖项季的热度。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Grasset / Goncourt first selection 2026",
        "sourceUrl": "",
        "selectionReason": "2026秋季龚古尔初选，法国畅销可见。",
        "author": {
            "name": "Thélyson Orélien",
            "localizedName": "泰利松·奥雷利安",
            "nationality": "海地/加拿大",
            "biographyZh": "奥雷利安以法语写作，2026年秋季因这部小说进入龚古尔初选并出现在畅销榜。关于作者更细的生平，宜以勒口为准。可以确定的是，法语世界在这一季把他放在了最亮的位置上。",
        },
        "fullDescriptionZh": "标题给出极限选择：这样，或死。小说把人物逼到几乎没有第三种语言的处境。作为秋季奖项季作品，它携带当代法语文学对生存、迁移或暴力的关注，具体情节以原书为准。阅读预期是强烈，而不是轻松。",
        "recommendationZh": "2026年法语秋季现象的入口。想跟踪龚古尔初选、并用原版感受这一季语气的人，应读榜首而不是只读评论。信息未全部细核的部分，已标待核验，不编造奖落谁家。",
        "audienceZh": "关注法语秋季奖项、能接受强烈当代题材的读者。不适合轻松度假阅读。",
    },
    {
        "matchTitle": "L'Autre moi",
        "languageCode": "fr",
        "chineseTitle": "另一个我",
        "publicationDate": "2026-04-28",
        "isbn13": "",
        "publisher": "Fleuve",
        "primaryGenre": "惊悚",
        "genres": ["惊悚", "悬疑"],
        "tags": ["高概念", "蒂利耶"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "现实若开始渗漏，侦探小说也会做梦。",
        "readingMoodZh": "迷宫、脑内、一层层翻面。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Fleuve, 2026-04-28",
        "sourceUrl": "",
        "selectionReason": "2026年4月28日独立长篇。",
        "author": {
            "name": "Franck Thilliez",
            "localizedName": "弗兰克·蒂利耶",
            "nationality": "法国",
            "biographyZh": "蒂利耶是法国高概念惊悚的代表，常把科学假说、警察程序和噩梦叠在一起。读者要有耐心跟随复杂结构。这一本暂时放下熟悉的警官组合，做一部更迷宫的独立作品。",
        },
        "fullDescriptionZh": "一条线里，日常开始不像日常；另一条线里，悬崖上的无名女尸要求调查。两条线互相渗透，直到读者无法安心区分梦与程序。小说长，层次多，靠不断推翻确定性前进。它不是温情犯罪，是让大脑过载的阅读。",
        "recommendationZh": "2026年法语类型里，这是给“我想被结构折磨”的读者的书。蒂利耶忠实于自己的 pledges：复杂、刺激、有点偏执。适合法语已较稳、能跟上多线的人。",
        "audienceZh": "高概念惊悚读者、蒂利耶旧作读者。不适合想读简单谁是凶手的人。",
    },
    {
        "matchTitle": "Je suis drôle",
        "languageCode": "fr",
        "chineseTitle": "我很有趣",
        "publicationDate": "2026-04-01",
        "isbn13": "",
        "publisher": "Gallimard",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["福恩基诺斯", "幽默"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "自称有趣的人，往往正在求救。",
        "readingMoodZh": "轻、准、带一点忧伤的好读。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Gallimard spring 2026",
        "sourceUrl": "",
        "selectionReason": "2026年春 Gallimard 新作；精确日待核。",
        "author": {
            "name": "David Foenkinos",
            "localizedName": "达维德·福恩基诺斯",
            "nationality": "法国",
            "biographyZh": "福恩基诺斯写感情与自我解嘲，句子流畅，结构像精心布置的客厅。他常被放在“好读文学”一侧：不炫技，却能让很多读者读完。新作标题像一句防御，内容则继续他对自尊与亲密的观察。",
        },
        "fullDescriptionZh": "一个需要被看成有趣的人，用幽默挡开真正要处理的情感。小说沿人物关系推进，轻盈里藏着难堪。它不追求黑暗高潮，追求那种在笑话说完之后的安静。法语好读，适合当作语言与人情的双重练习。",
        "recommendationZh": "2026年法语不必全是奖项季的重。福恩基诺斯提供另一种持续：温柔、清楚、略带讽刺。想保持法语阅读习惯、又不想每本都苦的人，这是稳定选择。",
        "audienceZh": "喜欢轻文学、人物关系与幽默的法语读者。不适合寻求残酷或高概念的人。",
    },
    {
        "matchTitle": "La révolte de la reine",
        "languageCode": "fr",
        "chineseTitle": "女王的反叛",
        "publicationDate": "2026-03-04",
        "isbn13": "",
        "publisher": "Hugo Publishing",
        "primaryGenre": "爱情",
        "genres": ["爱情", "历史"],
        "tags": ["浪漫", "历史改写", "三部曲"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "王后的轮廓还在，命运被重写了。",
        "readingMoodZh": "华丽、快、浪漫历史。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Hugo Publishing, 2026-03",
        "sourceUrl": "",
        "selectionReason": "2026年3月出版的畅销浪漫第一部。",
        "author": {
            "name": "Morgane Moncomble",
            "localizedName": "摩根·蒙孔布尔",
            "nationality": "法国",
            "biographyZh": "蒙孔布尔从网络写作走到法国最畅销作者之列，季节三部曲之后拥有极强的读者动员力。她写浪漫清楚、情感满、节奏快。新三部曲改走历史改写，以玛丽·安托瓦内特为灵感而不绑死史实。这是一种明确面向读者的法语。",
        },
        "fullDescriptionZh": "Inheritance 第一部把女性谱系写成可叛乱的历史浪漫。宫廷、欲望与权力用通俗戏剧的方式展开。它不是史学著作，是让读者沉浸的情感机器。人物要爱、要赢、要在规则里找到裂缝。读感接近连续剧的第一季：设定亮相，钩子留下。",
        "recommendationZh": "2026年法语大众阅读不能假装浪漫不存在。蒙孔布尔代表一种被年轻读者选中的原版法语。想提高流利度、并享受历史浪漫的人，不必羞愧地读它。",
        "audienceZh": "浪漫读者、历史改写爱好者、法语流行小说读者。不适合纯文学或史学严谨派。",
    },
    {
        "matchTitle": "Nous aussi",
        "languageCode": "fr",
        "chineseTitle": "我们也是",
        "publicationDate": "2026-08-01",
        "isbn13": "",
        "publisher": "Actes Sud",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "社会议题"],
        "tags": ["龚古尔初选", "集体"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "两个字的标题，把“我”改成“我们”。",
        "readingMoodZh": "集体、当代、奖项季的锋利。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Actes Sud / Goncourt 2026 first selection",
        "sourceUrl": "",
        "selectionReason": "2026秋季龚古尔初选。",
        "author": {
            "name": "Anne Godard",
            "localizedName": "安娜·戈达尔",
            "nationality": "法国",
            "biographyZh": "安娜·戈达尔的2026年长篇进入龚古尔初选，被秋季媒体称为具有冲击力的作品。更细的作者年表以勒口为准。可以确定的是，Actes Sud 把她放在这一季法语文学的主对话里。",
        },
        "fullDescriptionZh": "“我们也是”把个体经验扩成集体称谓。小说处理当代共同处境——具体事件以原书为准——阅读预期是政治的、情感的、不肯只停留在私人。奖项季作品常被讨论超过被阅读；这里把它当作原版文本邀请你自己读。",
        "recommendationZh": "与畅销悬疑并列，需要一本代表2026年法语文学奖路径的书。它可能比穆索难，也正因为难才构成这一季的另一面。适合愿意读当代法语文学、而不是只读类型的人。",
        "audienceZh": "法语文学读者、关注秋季奖项的人。不适合轻松类型读者。",
    },
    # ---------- Italian ----------
    {
        "matchTitle": "I convitati di pietra",
        "languageCode": "it",
        "chineseTitle": "石客",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Einaudi",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "悬疑"],
        "tags": ["斯特雷加", "命运契约"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "毕业之后，契约比友谊更记得你。",
        "readingMoodZh": "文学、命运游戏、奖项的重量。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Einaudi / Strega 2026 reports",
        "sourceUrl": "",
        "selectionReason": "2026斯特雷加相关新书；精确日期待核。",
        "author": {
            "name": "Michele Mari",
            "localizedName": "米歇尔·马里",
            "nationality": "意大利",
            "biographyZh": "米歇尔·马里是意大利当代最被文学读者尊敬的作者之一，博学、执拗、常把记忆与幻想织在一起。他的句子有密度，幽默也不轻松。2026年因《石客》站上斯特雷加的聚光灯，对马里读者是迟到的公共时刻。",
        },
        "fullDescriptionZh": "毕业后的诅咒契约把一群人继续绑在一起。石头客人这个神话意象变成当代命运游戏：谁还记得承诺，谁以为已经毕业。小说文学性强，情节像寓言那样运行。读它不是为了猜凶手，是为了看记忆如何变成债。",
        "recommendationZh": "2026年意大利语文学的主页之一。它证明奖项有时会奖给不容易的书。适合已有一定意大利语阅读力、并喜欢马里那种博学幻想的人。",
        "audienceZh": "意大利语文学读者、马里旧作读者。不适合寻求线性通俗情节的人。",
    },
    {
        "matchTitle": "Una splendida rovina",
        "languageCode": "it",
        "chineseTitle": "一座华丽的废墟",
        "publicationDate": "2026-09-01",
        "isbn13": "9788806270995",
        "publisher": "Einaudi",
        "primaryGenre": "文学小说",
        "genres": ["文学小说", "家庭"],
        "tags": ["乡村幻想", "爱情", "当代讽刺"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "买下一座没有窗户的房子，像买下一场误会。",
        "readingMoodZh": "讽刺、凉、三十岁的自我发明。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Einaudi ISBN 9788806270995",
        "sourceUrl": "",
        "selectionReason": "2026秋季 Einaudi 出版。",
        "author": {
            "name": "Vincenzo Latronico",
            "localizedName": "温琴佐·拉特罗尼科",
            "nationality": "意大利",
            "biographyZh": "拉特罗尼科因《完美》被国际看见，写当代中产的自我设计与幻觉。他冷静、精准、不给廉价同情。新作把“去乡村重新生活”的社交媒体梦想写成一座真的破房子。读者会被自己的品味笑话。",
        },
        "fullDescriptionZh": "一对刚相爱的三十岁人买下波罗的海边一千两百平米的废屋。没有窗户，屋顶勉强，人口一百九十二。装修、邻居、资金与热情同时崩塌。小说有两个版本的同一故事：勇敢的发明，或一次被房产网站诱导的出逃。废墟很华丽，幻觉更华丽。",
        "recommendationZh": "2026年意大利语当代小说里，这是最会刺痛“我们这种人”的一本。它延续《完美》的观察力，把爱情放进工程事故。适合读得懂讽刺、并愿意检讨自己生活美学的人。",
        "audienceZh": "当代文学读者、关心居住与中产幻想的人。不适合寻求田园治愈的读者。",
    },
    {
        "matchTitle": "Gli anni in bianco e nero",
        "languageCode": "it",
        "chineseTitle": "黑白岁月",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "North",
        "primaryGenre": "家庭",
        "genres": ["家庭", "历史"],
        "tags": ["普利亚", "畅销"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "彩色到来之前，村子已经把人分成明暗。",
        "readingMoodZh": "温暖、群体、通俗历史日常。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "North / 2026 Italian bestseller lists",
        "sourceUrl": "",
        "selectionReason": "2026年意大利畅销前列新作。",
        "author": {
            "name": "Francesca Giannone",
            "localizedName": "弗朗西斯卡·贾诺内",
            "nationality": "意大利",
            "biographyZh": "贾诺内因《女邮差》成为近年意大利最被阅读的通俗作者之一。她写南方村子、劳动妇女和缓慢的改变。新作延续那种让很多人读完的能力：人物清楚，时代可感，情感不阴暗到无法分享。",
        },
        "fullDescriptionZh": "黑白岁月把一个社群放回彩色摄影之前的伦理里。村子的规则、女人的工作、可见与不可见的阶层，构成长篇的日常纹理。它不是先锋，是让历史变成可跟随的生活。读者会感到熟悉的贾诺内：人多，心软，仍有冲突。",
        "recommendationZh": "2026年意大利语大众阅读的代表。想从《女邮差》继续、或想用原版意大利语读好读长篇的人，这是自然选择。它证明通俗不必浅薄，也可以是地方的记忆术。",
        "audienceZh": "贾诺内读者、喜欢南方村落与女性群像的人。不适合实验文学读者。",
    },
    {
        "matchTitle": "Calde le pere",
        "languageCode": "it",
        "chineseTitle": "热梨",
        "publicationDate": "2026-08-28",
        "isbn13": "9791223286869",
        "publisher": "Giunti",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["遗作", "雷诺河", "地方志"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "一声叫卖，把整条河叫回来。",
        "readingMoodZh": "短、地方、遗作的清亮。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Giunti ISBN 9791223286869，2026-08-28 posthumous",
        "sourceUrl": "",
        "selectionReason": "2026年8月28日遗作出版。",
        "author": {
            "name": "Francesco Guccini",
            "localizedName": "弗朗切斯科·古奇尼",
            "nationality": "意大利",
            "biographyZh": "古奇尼是意大利创作歌手与散文、小说作者，写故乡、河流和口头传统。他于二〇二六年八月去世前仍在完成这本书。读者会听到歌里那种地名的感情：不是旅游，是发音本身带着爱。",
        },
        "fullDescriptionZh": "炎热的日子，自行车上的女孩喊“热梨！”。由此展开雷诺河、卡萨莱基奥与一个贞洁少女的民间传闻。小说短，分画面，像被口头传统推着走。妓女与后来像妇科医生的女人形成对照。地方比情节更重要：河是记忆的语法。",
        "recommendationZh": "2026年意大利语里，这是不能用畅销逻辑衡量的一本。它短，却把一条河的声音留下来。喜欢歌、地方志和口头故事的人，会觉得这是告别，也是作品。",
        "audienceZh": "古奇尼听众与读者、喜欢意大利地方叙事的人。不适合寻求长篇情节的人。",
    },
    {
        "matchTitle": "Malinconico Blues",
        "languageCode": "it",
        "chineseTitle": "忧郁蓝调",
        "publicationDate": "2026-09-22",
        "isbn13": "9788806264697",
        "publisher": "Einaudi",
        "primaryGenre": "推理",
        "genres": ["推理", "家庭"],
        "tags": ["律师", "那不勒斯", "幽默"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "律师想降档生活，案件偏不让。",
        "readingMoodZh": "贫嘴、温暖、那不勒斯的日常罪案。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Einaudi ISBN 9788806264697",
        "sourceUrl": "",
        "selectionReason": "2026年9月22日系列新作。",
        "author": {
            "name": "Diego De Silva",
            "localizedName": "迭戈·德席尔瓦",
            "nationality": "意大利",
            "biographyZh": "德席尔瓦以律师 Vincenzo Malinconico 系列写出一种意大利式幽默罪案：人很废，话很多，心却不坏。那不勒斯在他笔下不是风景，是口气。读者爱这个人物，像爱一个会把自己搞砸的朋友。",
        },
        "fullDescriptionZh": "马林科尼科想离开大名鼎鼎的律所，回到失败但自由的节奏。一个英俊却平庸的演员来办离婚，随即卷入更严重的指控。伴侣、顾问、一只突然出现的狗，把生活写成即兴演奏。案件是骨架，跑题才是音乐。",
        "recommendationZh": "2026年秋季意大利语通俗阅读的快乐来源。它让罪案保持人味。想用原版意大利语读对话、并享受系列人物的人，这是明确选项。",
        "audienceZh": "系列读者、喜欢幽默法律小说的人。不适合硬派noir读者。",
    },
    {
        "matchTitle": "La ragazzina",
        "languageCode": "it",
        "chineseTitle": "那个小姑娘",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Feltrinelli",
        "primaryGenre": "历史",
        "genres": ["历史", "文学小说"],
        "tags": ["贞德", "坎皮耶洛", "女声"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "圣女之前，她只是一个不肯变小的女孩。",
        "readingMoodZh": "短、烈、历史被写成当下。",
        "verificationStatus": "verified",
        "verifiedAt": "2026-09-17",
        "sourceName": "Feltrinelli / Campiello 2026 cinquina",
        "sourceUrl": "",
        "selectionReason": "2026坎皮耶洛决赛作品。",
        "author": {
            "name": "Valeria Parrella",
            "localizedName": "瓦莱里娅·帕雷拉",
            "nationality": "意大利",
            "biographyZh": "帕雷拉写那不勒斯的教育、女性与公共勇气，句子短，立场清。她把贞德写成“小姑娘”，不是为了减历史，是为了把历史从圣像里救出来。读者会感到一种当代愤怒：女孩认真时，男人就想把她缩小。",
        },
        "fullDescriptionZh": "贞德骑马、祈祷、穿男装、把太子送上王位。小说不断提醒：在成为圣女、疯子或象征之前，她有兄弟、母亲和梦。战争像所有战争，围城像今天的围城。短篇体量把史诗压成一把尖的声音。她不在乎被怎么叫，她有任务。",
        "recommendationZh": "2026年意大利语里，这是把历史写成女童政治的少见作品。适合愿意读短而密、并关心女孩如何被权力描述的人。它不是传记课本，是一篇当代檄文。",
        "audienceZh": "历史文学读者、女性主义读者、帕雷拉读者。不适合寻求宫廷长篇娱乐的人。",
    },
    {
        "matchTitle": "Il Bufalo e Sammarzano",
        "languageCode": "it",
        "chineseTitle": "水牛与萨马扎诺",
        "publicationDate": "2026-10-13",
        "isbn13": "",
        "publisher": "Rizzoli",
        "primaryGenre": "推理",
        "genres": ["推理"],
        "tags": ["那不勒斯", "美食", "新系列"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "厨师不说话，菜会替他作证。",
        "readingMoodZh": "香、闹、罪案混着风俗喜剧。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "ANSA 2026-08-07 / Rizzoli 秋季预告",
        "sourceUrl": "",
        "selectionReason": "2026年10月中旬刊行预告；ISBN尚未公布，封面待补。",
        "author": {
            "name": "Maurizio de Giovanni",
            "localizedName": "毛里齐奥·德乔瓦尼",
            "nationality": "意大利",
            "biographyZh": "德乔瓦尼以一九三〇年代那不勒斯探长系列闻名，也写当代那不勒斯的食物与罪。他产量高，地方感稳定。新系列把坏脾气厨师放进 noir 与风俗喜剧之间，让读者先闻到厨房，再看到案件。",
        },
        "fullDescriptionZh": "那不勒斯厨师用菜沟通，调查则在厨房的节奏里发生。紧张与笑点并置，城市的味道比枪更先到。作为系列第一部，它负责建立人物：谁沉默，谁饶舌，谁负责尝。罪案是引线，风俗是世界。",
        "recommendationZh": "2026年意大利语类型阅读的快乐入口。德乔瓦尼知道读者为什么回来：地方、食物、人。想用原版意大利语读轻松罪案的人，不必从最黑暗的noir开始。",
        "audienceZh": "德乔瓦尼读者、喜欢美食与城市风俗的推理读者。不适合极简文学读者。",
    },
    {
        "matchTitle": "Ci basterà mangiare il vento",
        "languageCode": "it",
        "chineseTitle": "我们吃风就够了",
        "publicationDate": "2026-01-01",
        "isbn13": "",
        "publisher": "Mondadori",
        "primaryGenre": "成长",
        "genres": ["成长", "家庭"],
        "tags": ["旅行", "自我", "畅销"],
        "coverImage": "/covers/placeholder.svg",
        "editorQuoteZh": "吃风，是一种把轻当成勇气的说法。",
        "readingMoodZh": "轻、旅行、自我成长的口语。",
        "verificationStatus": "pending",
        "verifiedAt": "2026-09-17",
        "sourceName": "Mondadori / 2026 Italian charts",
        "sourceUrl": "",
        "selectionReason": "2026年意大利畅销前列新作。",
        "author": {
            "name": "Gianluca Gotto",
            "localizedName": "詹卢卡·戈托",
            "nationality": "意大利",
            "biographyZh": "戈托写旅行、自我与年轻读者能迅速进入的情感。他的书常在畅销榜与“生活建议”之间。文学上有人觉得轻，对想用意大利语读当下口气的人，却是一条宽路。新加坡与都灵的对照，让移动成为主题。",
        },
        "fullDescriptionZh": "吃风就够了：一种把不安定说成足够的生活态度。小说在城市之间移动，处理选择、亲密和自我叙述。它面向广大年轻读者，句子好懂，情感直接。不是社会解剖，是一种被很多同代人分享的语气。",
        "recommendationZh": "2026年意大利语大众阅读的年轻一面。要理解这一年书店里在卖什么，不能只看斯特雷加。适合想读好懂的原版、并对旅行与自我主题有共鸣的人。",
        "audienceZh": "年轻读者、旅行与自我成长主题爱好者。不适合寻求厚重文学或黑暗类型的人。",
    },
]

